site_name: Noebs APIs

repo_url: https://github.com/adonese/noebs-docs

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - toc:
     permalink: ¶


theme:
  name: material
  logo: assets/logo2.png
  favicon: assets/favicon.ico
  # custom_dir: overrides

nav:
  - index.md
  - Using Special Payment: biller_system.md
  - JSON API: s2s.md
  - IFrame / web interface: iframe.md
  - Encryption: encryption.md
  - Our SDKs:
    - Java SDK: java.md
    - Java Script SDK: js.md
    - Flutter / Dart SDK: flutter.md
    - Go SDK: go.sdk
  - POS / Kiosks: pos.md
