site_name: Noebs APIs

repo_url: https://github.com/adonese/noebs-docs

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - toc:
     permalink: ¶
  - meta
  - pymdownx.snippets
  - admonition
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noebs
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/noebs
    - icon: fontawesome/brands/github
      link: https://github.com/noebs

copyright: Copyright &copy; 2018 - 2021 Mohamed Yousif & Co
theme:
  name: material
  logo: assets/logo2.png
  favicon: assets/favicon.ico
  # custom_dir: overrides

nav:
  - index.md
  - Using Special Payment: biller_system.md
  - JSON API: s2s.md
  - IFrame / web interface: iframe.md
  - Encryption: encryption.md
  - Our SDKs:
    - Java SDK: java.md
    - Java Script SDK: js.md
    - Flutter / Dart SDK: flutter.md
    - Go SDK: go.sdk
  - POS / Kiosks: pos.md
  - Cashouts and rewards points: cashout.md
  - Self hosting noebs: installation.md
